### ISSUE TITLE
Cannot find symbol

### ISSUE THREAD

**Issue by buckle2000** [BarnabyShearer/pynfc#1]
```
>>> import pynfc
AttributeError: /usr/lib/x86_64-linux-gnu/libnfc.so: undefined symbol: cfree
```

**Comment by buckle2000** [comment]
http://man7.org/linux/man-pages/man3/cfree.3.html
       The cfree() function was removed from glibc in version 2.26.

**Comment by BarnabyShearer** [comment]
Thank you for reporting, this indeed was using an older glibc. I have made a new 0.1.1 release which should resolve this and hopefully will work with most common libnfc.so.
